# Create a workflow that triggers manually and:
# 1. Print our SLOGAN
name: secret stuff
on: 
  workflow_dispatch:
   inputs:
     num:
       type: string
       description: "select number to guess"
       default: "3"
     
jobs:
  print-slogan:
    runs-on: ubuntu-latest
    env:
      SLOGAN: ${{ vars.SLOGAN }}
    steps:
      - run: echo ${{ vars.SLOGAN }}
      - run: echo $SLOGAN

# 2. Guess our MY_MAGIC_NUMBER
  guess-magic-number:
    runs-on: ubuntu-latest
    env:
      MY_MAGIC_NUMBER: ${{ secrets.MY_MAGIC_NUMBER }}
    steps:
      - name: Print Magic Number
        run: echo ${{ secrets.MY_MAGIC_NUMBER }}
        
      - name: Print Magic Number With environment variable
        run: echo ($MY_MAGIC_NUMBER + 1)

      - name: Guess Magic Number
        run: |
          if ["${{ secrets.MY_MAGIC_NUMBER }}" = "${{ inputs.num }}"]; then
            echo "Yay! The magic number was:  ${{ inputs.num }}"
          fi







        
